name: FarylizerPlugin
version: ${project.version}
main: la.FarylizerPlugin
api-version: 1.17
author: Gamestyler1999
commands:
   farylizer:
      description: Gibt dem Spieler den Farylizer
   generateCube:
      description: erstellt eine Testfläche 
     